apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shiksha

resources:
  - ../../

images:
  - name: shiksha-sarthi
    newName: REPLACE_ME
    newTag: REPLACE_ME

commonLabels:
  environment: production
  deployed-by: github-actions
